add_lunch_combo aosip_flo-user
add_lunch_combo aosip_grouper-userdebug
add_lunch_combo aosip_hammerhead-user
add_lunch_combo aosip_mako-userdebug
add_lunch_combo aosip_manta-userdebug
add_lunch_combo aosip_shamu-user

